
services:
  postgres-db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=postgresDev
      - POSTGRES_DB=culinaryCode
    ports:
      - '5432:5432'
