
CREATE SCHEMA IF NOT EXISTS recipes;

CREATE TABLE IF NOT EXISTS recipes.recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    user_id BIGINT NOT NULL,
    method TEXT,
    preparation TEXT,
    servings INT,
    prep_time INT,
    cook_time INT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes.recipe_cuisines (
    recipe_id BIGINT
        CONSTRAINT fk_recipe_cuisines_recipe_id
            REFERENCES recipes.recipe(id),
    cuisine_name TEXT,
    PRIMARY KEY (recipe_id, cuisine_name)
);

CREATE TABLE IF NOT EXISTS recipes.ingredients (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recipes.recipe_ingredients (
    recipe_id BIGINT
        CONSTRAINT fk_recipe_ingredients_recipe_id
            REFERENCES recipes.recipe(id),
    ingredient_id BIGINT
        CONSTRAINT fk_recipe_ingredients_ingredient_id
            REFERENCES recipes.ingredients(id),
    type TEXT,
    quantity INT,
    unit TEXT
);
