
CREATE SCHEMA IF NOT EXISTS recipes;

CREATE TABLE IF NOT EXISTS recipes.recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    user_id BIGINT NOT NULL,
    method TEXT,
    preparation TEXT,
    servings INT,
    prep_time INT,
    cook_time INT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes.recipe_cuisines (
    recipe_id BIGINT,
    cuisine_name TEXT,
    PRIMARY KEY (recipe_id, cuisine_name),
    FOREIGN KEY (recipe_id) REFERENCES recipes.recipe(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS recipes.ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recipes.recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT,
    ingredient_id BIGINT,
    notes TEXT,
    quantity DECIMAL(10,2),
    unit TEXT,
    FOREIGN KEY (recipe_id) REFERENCES recipes.recipe(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES recipes.ingredients(id) ON DELETE CASCADE
);
